// <auto-generated />
using System;
using Dersakis.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace app.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261009151813_AddWatchSessions")]
    partial class AddWatchSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("VideoPublishSeq");

            modelBuilder.Entity("Dersakis.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UX_Courses_Slug");

                    b.ToTable("Courses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0b1e0001-0000-4000-8000-000000000001"),
                            CreatedAtUtc = new DateTime(2026, 10, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Matematik 1",
                            Slug = "matematik-1",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = new Guid("0b1e0001-0000-4000-8000-000000000002"),
                            CreatedAtUtc = new DateTime(2026, 10, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Fizik 1",
                            Slug = "fizik-1",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = new Guid("0b1e0001-0000-4000-8000-000000000003"),
                            CreatedAtUtc = new DateTime(2026, 10, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Genel Kimya",
                            Slug = "genel-kimya",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = new Guid("0b1e0001-0000-4000-8000-000000000004"),
                            CreatedAtUtc = new DateTime(2026, 10, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Anatomi",
                            Slug = "anatomi",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = new Guid("0b1e0001-0000-4000-8000-000000000005"),
                            CreatedAtUtc = new DateTime(2026, 10, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Hücre Biyolojisi",
                            Slug = "hucre-biyolojisi",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("Dersakis.Domain.Entities.CreditTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("BalanceAfter")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<byte>("Reason")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("RefId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAtUtc")
                        .HasDatabaseName("IX_CreditTransactions_UserId_CreatedAtUtc");

                    b.HasIndex("UserId", "Reason", "RefId")
                        .IsUnique()
                        .HasDatabaseName("UX_CreditTransactions_UserId_Reason_RefId");

                    b.ToTable("CreditTransactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_CreditTransactions_BalanceAfter_NonNegative", "[BalanceAfter] >= 0");
                        });
                });

            modelBuilder.Entity("Dersakis.Domain.Entities.IdempotencyKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("varchar(64)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<byte[]>("RequestHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<byte[]>("ResponseBody")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_IdempotencyKeys_CreatedAtUtc");

                    b.HasIndex("UserId", "Key")
                        .IsUnique()
                        .HasDatabaseName("UX_IdempotencyKeys_UserId_Key");

                    b.ToTable("IdempotencyKeys", (string)null);
                });

            modelBuilder.Entity("Dersakis.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("CreditBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DailyEarned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateOnly?>("DailyEarnedDay")
                        .HasColumnType("date");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LockoutEndUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_NormalizedEmail");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_CreditBalance_NonNegative", "[CreditBalance] >= 0");

                            t.HasCheckConstraint("CK_Users_DailyEarned_NonNegative", "[DailyEarned] >= 0");
                        });
                });

            modelBuilder.Entity("Dersakis.Domain.Entities.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DurationMs")
                        .HasColumnType("int");

                    b.Property<long?>("PublishSeq")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("PublishSeq")
                        .IsUnique()
                        .IsDescending()
                        .HasDatabaseName("UX_Videos_PublishSeq")
                        .HasFilter("[PublishSeq] IS NOT NULL");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("PublishSeq"), new[] { "Status", "CourseId" });

                    b.HasIndex("CreatorId", "CreatedAtUtc")
                        .HasDatabaseName("IX_Videos_CreatorId_CreatedAtUtc");

                    b.ToTable("Videos", null, t =>
                        {
                            t.HasCheckConstraint("CK_Videos_Published_Complete", "[Status] <> 2 OR ([DurationMs] > 0 AND [StoragePath] IS NOT NULL AND [PublishSeq] IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Dersakis.Domain.Entities.VideoOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId")
                        .IsUnique()
                        .HasDatabaseName("UX_VideoOptions_OneCorrectPerQuestion")
                        .HasFilter("[IsCorrect] = 1");

                    b.ToTable("VideoOptions", (string)null);
                });

            modelBuilder.Entity("Dersakis.Domain.Entities.VideoQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<byte>("Position")
                        .HasColumnType("tinyint");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VideoId", "Position")
                        .IsUnique()
                        .HasDatabaseName("UX_VideoQuestions_VideoId_Position");

                    b.ToTable("VideoQuestions", null, t =>
                        {
                            t.HasCheckConstraint("CK_VideoQuestions_Position", "[Position] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("Dersakis.Domain.Entities.WatchSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("LastHeartbeatAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("LastPositionMs")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VideoDurationMs")
                        .HasColumnType("int");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WatchedMs")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_WatchSessions_OneActivePerUser")
                        .HasFilter("[Status] = 1");

                    b.HasIndex("VideoId");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("IX_WatchSessions_Status_CreatedAtUtc");

                    b.HasIndex("UserId", "VideoId")
                        .IsUnique()
                        .HasDatabaseName("UX_WatchSessions_OneCompletedPerVideo")
                        .HasFilter("[Status] = 2");

                    b.ToTable("WatchSessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_WatchSessions_Progress", "[WatchedMs] >= 0 AND [WatchedMs] <= [VideoDurationMs] AND [LastPositionMs] >= 0 AND [LastPositionMs] <= [VideoDurationMs]");
                        });
                });

            modelBuilder.Entity("Dersakis.Domain.Entities.CreditTransaction", b =>
                {
                    b.HasOne("Dersakis.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dersakis.Domain.Entities.IdempotencyKey", b =>
                {
                    b.HasOne("Dersakis.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dersakis.Domain.Entities.Video", b =>
                {
                    b.HasOne("Dersakis.Domain.Entities.Course", null)
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dersakis.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dersakis.Domain.Entities.VideoOption", b =>
                {
                    b.HasOne("Dersakis.Domain.Entities.VideoQuestion", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dersakis.Domain.Entities.VideoQuestion", b =>
                {
                    b.HasOne("Dersakis.Domain.Entities.Video", null)
                        .WithMany("Questions")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dersakis.Domain.Entities.WatchSession", b =>
                {
                    b.HasOne("Dersakis.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dersakis.Domain.Entities.Video", null)
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Dersakis.Domain.Entities.Video", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Dersakis.Domain.Entities.VideoQuestion", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
